version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps

    working_directory: ~/morpheus

    environment:
      CODECOV_TOKEN: "d951cafc-0460-4912-aa07-f06923af1bd3"

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deps.edn" }}
        # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: clojure -A:test -Spath
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}
      - run: clojure -A:test -m kaocha.runner
      - run: clojure -A:test -m kaocha.runner --plugin cloverage --codecov
      - codecov/upload:
          file: target/coverage/codecov.json
